name: Create version in npm

on:
  workflow_dispatch:
    inputs:
      VersionRelease:
        type: choice
        required: true
        description: 'Chose version to update'
        default: 'patch'
        options:
        - major
        - minor
        - patch

jobs:
  version:
    name: Create new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_TOKEN }}
      
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GH_ACTIONS_GPG_KEY }}
          passphrase: ${{ secrets.GH_ACTIONS_GPG_PASS }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Set up yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.5
          token: ${{ secrets.NODE_AUTH_TOKEN }}
          registry-url: "https://registry.npmjs.org"
      
      - name: Update version and build
        run: |
          yarn install
          npm version ${{ github.event.inputs.VersionRelease }}
          yarn build
          npm ls --depth=0
          git status 
          git diff
          git add docs.json
          git commit -m"Change files from new ${{ github.event.inputs.VersionRelease }} release."
          git push
      
#      - name: Publish npm package
#        run: |
#          npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
#
